'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AcademiaAsistenciaTipoPuntaje
    Public Property IDAcademiaAsistenciaTipo As Byte
    Public Property FechaInicio As Date
    Public Property Puntaje As Byte

    Public Overridable Property AcademiaAsistenciaTipo As AcademiaAsistenciaTipo

End Class
