'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Area
    Public Property IDArea As Byte
    Public Property Codigo As String
    Public Property Nombre As String
    Public Property EsActivo As Boolean

    Public Overridable Property Elemento As ICollection(Of Elemento) = New HashSet(Of Elemento)

End Class
