'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CajaArqueoDetalle
    Public Property IDCaja As Byte
    Public Property IDArqueo As Integer
    Public Property IDDetalle As Short
    Public Property NumeroComprobante As String
    Public Property Fecha As Date
    Public Property Proveedor As String
    Public Property Detalle As String
    Public Property Importe As Decimal
    Public Property Notas As String

    Public Overridable Property CajaArqueo As CajaArqueo

End Class
