'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CajaArqueo
    Public Property IDCaja As Byte
    Public Property IDArqueo As Integer
    Public Property SaldoInicial As Decimal
    Public Property ImporteAsignado As Decimal
    Public Property FechaCierre As Nullable(Of Date)
    Public Property Notas As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Caja As Caja
    Public Overridable Property CajaArqueoDetalles As ICollection(Of CajaArqueoDetalle) = New HashSet(Of CajaArqueoDetalle)
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
