'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ChequeMotivoRechazo
    Public Property IDChequeMotivoRechazo As Byte
    Public Property CodigoNacha As String
    Public Property Nombre As String
    Public Property NombreCompleto As String
    Public Property EsActivo As Boolean

    Public Overridable Property Cheques As ICollection(Of Cheque) = New HashSet(Of Cheque)

End Class
