'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CompraOrdenFactura
    Public Property IDCompraOrden As Integer
    Public Property IDCompraFactura As Integer
    Public Property ImporteAplicado As Decimal
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property CompraFactura As CompraFactura
    Public Overridable Property CompraOrden As CompraOrden
    Public Overridable Property Usuario As Usuario
    Public Overridable Property Usuario1 As Usuario

End Class
