'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Localidad
    Public Property IDProvincia As Byte
    Public Property IDLocalidad As Short
    Public Property Nombre As String
    Public Property CodigoPostal As Nullable(Of Short)
    Public Property IDPartido As Nullable(Of Short)

    Public Overridable Property Provincia As Provincia
    Public Overridable Property Cuartel As ICollection(Of Cuartel) = New HashSet(Of Cuartel)
    Public Overridable Property PersonasLaboral As ICollection(Of Persona) = New HashSet(Of Persona)
    Public Overridable Property PersonasParticular As ICollection(Of Persona) = New HashSet(Of Persona)
    Public Overridable Property PersonaCapacitacion As ICollection(Of PersonaCapacitacion) = New HashSet(Of PersonaCapacitacion)
    Public Overridable Property PersonaFamiliar As ICollection(Of PersonaFamiliar) = New HashSet(Of PersonaFamiliar)
    Public Overridable Property Partido As Partido
    Public Overridable Property Proveedores As ICollection(Of Proveedor) = New HashSet(Of Proveedor)

End Class
