'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Modulo
    Public Property IDModulo As Byte
    Public Property Nombre As String
    Public Property EsActivo As Boolean
    Public Property Orden As Nullable(Of Byte)

    Public Overridable Property ReporteGrupos As ICollection(Of ReporteGrupo) = New HashSet(Of ReporteGrupo)

End Class
