Module Parametros
    'SISTEMA
    Friend Const INTERNET_PROXY As String = "INTERNET_PROXY"

    ' APLICACIÓN
    Friend Const APPLICATION_DATABASE_GUID As String = "APPLICATION_DATABASE_GUID"
    Friend Const LICENSE_COMPANY_NAME As String = "LICENSE_COMPANY_NAME"
    Friend Const USER_PASSWORD_MINIMUM_LENGHT As String = "USER_PASSWORD_MINIMUM_LENGHT"
    Friend Const USER_PASSWORD_SECURE_REQUIRED As String = "USER_PASSWORD_SECURE_REQUIRED"
    Friend Const EMAIL_VALIDATION_REGULAREXPRESSION As String = "EMAIL_VALIDATION_REGULAREXPRESSION"

    ' VALORES PREDETERMINADOS
    Friend Const DEFAULT_PROVINCIA_ID As String = "DEFAULT_PROVINCIA_ID"
    Friend Const DEFAULT_LOCALIDAD_ID As String = "DEFAULT_LOCALIDAD_ID"
    Friend Const DEFAULT_CODIGOPOSTAL As String = "DEFAULT_CODIGOPOSTAL"
    Friend Const DEFAULT_CATEGORIAIVA_ID As String = "DEFAULT_CATEGORIAIVA_ID"
    Friend Const DEFAULT_MONEDA_ID As String = "DEFAULT_MONEDA_ID"
    Friend Const DEFAULT_DOCUMENTOTIPO_ID As String = "DEFAULT_DOCUMENTOTIPO_ID"

    ' VARIOS
    Friend Const COMPROBANTE_ENTIDAD_MAYUSCULAS As String = "COMPROBANTE_ENTIDAD_MAYUSCULAS"
    Friend Const CONSUMIDORFINAL_DOCUMENTOTIPO_ID As String = "CONSUMIDORFINAL_DOCUMENTOTIPO_ID"
    Friend Const CONSUMIDORFINAL_DOCUMENTONUMERO As String = "CONSUMIDORFINAL_DOCUMENTONUMERO"

    ' AFIP WEB SERVICES
    Friend Const AFIP_WS_AA_HOMOLOGACION As String = "AFIP_WS_AA_HOMOLOGACION"
    Friend Const AFIP_WS_AA_PRODUCCION As String = "AFIP_WS_AA_PRODUCCION"
    Friend Const AFIP_WS_FE_HOMOLOGACION As String = "AFIP_WS_FE_HOMOLOGACION"
    Friend Const AFIP_WS_FE_PRODUCCION As String = "AFIP_WS_FE_PRODUCCION"

    ' EMPRESA
    Friend Const EMPRESA_CUIT As String = "EMPRESA_CUIT"
    Friend Const EMPRESA_RAZONSOCIAL As String = "EMPRESA_RAZONSOCIAL"
    Friend Const EMPRESA_DOMICILIOFISCAL_DIRECCION As String = "EMPRESA_DOMICILIOFISCAL_DIRECCION"
    Friend Const EMPRESA_DOMICILIOFISCAL_CODIGOPOSTAL As String = "EMPRESA_DOMICILIOFISCAL_CODIGOPOSTAL"
    Friend Const EMPRESA_DOMICILIOFISCAL_LOCALIDAD_ID As String = "EMPRESA_DOMICILIOFISCAL_LOCALIDAD_ID"
    Friend Const EMPRESA_DOMICILIOFISCAL_PROVINCIA_ID As String = "EMPRESA_DOMICILIOFISCAL_PROVINCIA_ID"
    Friend Const EMPRESA_CATEGORIAIVA_ID As String = "EMPRESA_CATEGORIAIVA_ID"
    Friend Const EMPRESA_IIBB_NUMERO As String = "EMPRESA_IIBB_NUMERO"
    Friend Const EMPRESA_INICIO_ACTIVIDAD As String = "EMPRESA_INICIO_ACTIVIDAD"

    ' PARENTESCOS
    Friend Const PARENTESCO_ID_PADRE As String = "PARENTESCO_ID_PADRE"
    Friend Const PARENTESCO_ID_MADRE As String = "PARENTESCO_ID_MADRE"
    Friend Const PARENTESCO_ID_HIJO As String = "PARENTESCO_ID_HIJO"

    ' VARIOS
    Friend Const PERSONA_CALIFICACION_INSTANCIA_CANTIDAD As String = "PERSONA_CALIFICACION_INSTANCIA_CANTIDAD"

    ' REPORTES
    Friend Const REPORTE_ID_PERSONA_FICHA As String = "REPORTE_ID_PERSONA_FICHA"
    Friend Const REPORTE_ID_PERSONA_LISTADO As String = "REPORTE_ID_PERSONA_LISTADO"
    Friend Const REPORTE_ID_PERSONA_PLANILLAANUALCALIFICACIONES As String = "REPORTE_ID_PERSONA_PLANILLAANUALCALIFICACIONES"
    Friend Const REPORTE_ID_PERSONA_SANCIONDISCIPLINARIA As String = "REPORTE_ID_PERSONA_SANCIONDISCIPLINARIA"
    Friend Const REPORTE_ID_PERSONA_LICENCIA As String = "REPORTE_ID_PERSONA_LICENCIA"

    ' USUARIOS
    Friend Const USUARIO_INICIOSESION_ALARMA_AVISO_MOSTRAR As String = "USUARIO_INICIOSESION_ALARMA_AVISO_MOSTRAR"
End Module
