'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Partido
    Public Property IDPartido As Short
    Public Property Nombre As String
    Public Property IDProvincia As Byte
    Public Property CodigoProvincial As Nullable(Of Byte)

    Public Overridable Property Localidades As ICollection(Of Localidad) = New HashSet(Of Localidad)
    Public Overridable Property Provincia As Provincia

End Class
