'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaLicenciaConducirCategoria
    Public Property IDPersona As Integer
    Public Property IDLicenciaConducirCategoria As Byte
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date

    Public Overridable Property Persona As Persona
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property LicenciaConducirCategoria As LicenciaConducirCategoria

End Class
