'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaVehiculo
    Public Property IDPersona As Integer
    Public Property IDVehiculo As Byte
    Public Property IDVehiculoTipo As Byte
    Public Property Dominio As String
    Public Property IDVehiculoMarca As Nullable(Of Short)
    Public Property Modelo As String
    Public Property Anio As Nullable(Of Short)
    Public Property VerificacionVencimiento As Date
    Public Property IDVehiculoCompaniaSeguro As Nullable(Of Short)
    Public Property SeguroPolizaNumero As String
    Public Property SeguroVencimiento As Date
    Public Property Notas As String
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property VehiculoCompaniaSeguro As VehiculoCompaniaSeguro
    Public Overridable Property VehiculoMarca As VehiculoMarca
    Public Overridable Property VehiculoTipo As VehiculoTipo
    Public Overridable Property Persona As Persona

End Class
