'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaCalificacion
    Public Property IDPersona As Integer
    Public Property Anio As Short
    Public Property InstanciaNumero As Byte
    Public Property IDCalificacionConcepto As Byte
    Public Property Calificacion As Byte
    Public Property Notas As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property CalificacionConcepto As CalificacionConcepto
    Public Overridable Property Persona As Persona

End Class
