'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaHorarioLaboral
    Public Property IDPersona As Integer
    Public Property DiaSemana As Byte
    Public Property Turno1Desde As Nullable(Of System.TimeSpan)
    Public Property Turno1Hasta As Nullable(Of System.TimeSpan)
    Public Property Turno2Desde As Nullable(Of System.TimeSpan)
    Public Property Turno2Hasta As Nullable(Of System.TimeSpan)
    Public Property Notas As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property Persona As Persona

End Class
