'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SiniestroAsistenciaTipoPuntaje
    Public Property IDSiniestroAsistenciaTipo As Byte
    Public Property IDSiniestroAsistenciaTipoPuntaje As Byte
    Public Property FechaInicio As Date
    Public Property PuntajeClaveVerde As Decimal
    Public Property PuntajeClaveAzul As Decimal
    Public Property PuntajeClaveNaranja As Decimal
    Public Property PuntajeClaveRoja As Decimal

    Public Overridable Property SiniestroAsistenciaTipo As SiniestroAsistenciaTipo

End Class
