'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SiniestroAsistencia
    Public Property IDSiniestro As Integer
    Public Property IDPersona As Integer
    Public Property IDSiniestroAsistenciaTipo As Byte

    Public Overridable Property SiniestroAsistenciaTipo As SiniestroAsistenciaTipo
    Public Overridable Property Persona As Persona
    Public Overridable Property Siniestro As Siniestro

End Class
