'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipografiaEstilo
    Public Property IDTipografiaEstilo As Byte
    Public Property Nombre As String
    Public Property Tamanio As Decimal
    Public Property Negrita As Boolean
    Public Property Italica As Boolean
    Public Property Subrayada As Boolean
    Public Property Tachada As Boolean

    Public Overridable Property Reportes As ICollection(Of Reporte) = New HashSet(Of Reporte)
    Public Overridable Property ReporteCampo As ICollection(Of ReporteCampo) = New HashSet(Of ReporteCampo)

End Class
