'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Unidad
    Public Property IDUnidad As Short
    Public Property Numero As Short
    Public Property Marca As String
    Public Property Modelo As String
    Public Property MarcaModelo As String
    Public Property NumeroMarcaModelo As String
    Public Property EsImportado As Nullable(Of Boolean)
    Public Property Anio As Short
    Public Property NumeroMotor As String
    Public Property NumeroChasis As String
    Public Property Dominio As String
    Public Property IDUnidadTipo As Byte
    Public Property IDUnidadUso As Byte
    Public Property IDCombustibleTipo As Nullable(Of Byte)
    Public Property FechaAdquisicion As Nullable(Of Date)
    Public Property KilometrajeInicial As Nullable(Of Integer)
    Public Property CapacidadAguaLitros As Nullable(Of Integer)
    Public Property IDCuartel As Byte
    Public Property EsPropio As Boolean
    Public Property VerificacionVencimiento As Nullable(Of Date)
    Public Property Notas As String
    Public Property EsActivo As Boolean
    Public Property IDUnidadBajaMotivo As Nullable(Of Byte)
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UnidadTipo As UnidadTipo
    Public Overridable Property CombustibleTipo As CombustibleTipo
    Public Overridable Property Cuartel As Cuartel
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property Ubicacion As ICollection(Of Ubicacion) = New HashSet(Of Ubicacion)
    Public Overridable Property UnidadUso As UnidadUso
    Public Overridable Property UnidadBajaMotivo As UnidadBajaMotivo

End Class
