USE [CSBomberos]
GO
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (1, N'Buenos Aires')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (2, N'Catamarca')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (16, N'Chaco')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (17, N'Chubut')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (100, N'Ciudad Autónoma de Buenos Aires')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (3, N'Córdoba')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (4, N'Corrientes')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (5, N'Entre Ríos')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (18, N'Formosa')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (6, N'Jujuy')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (21, N'La Pampa')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (8, N'La Rioja')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (7, N'Mendoza')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (19, N'Misiones')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (20, N'Neuquén')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (22, N'Río Negro')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (9, N'Salta')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (10, N'San Juan')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (11, N'San Luis')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (23, N'Santa Cruz')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (12, N'Sante Fe')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (13, N'Santiago del Estero')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (24, N'Tierra del Fuego e Islas del Atlántico Sur')
INSERT [dbo].[Provincia] ([IDProvincia], [Nombre]) VALUES (14, N'Tucumán')
