'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CSBomberos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconAplicacion() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconAplicacion", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAcademia32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAcademia32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAceptar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAceptar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAfipChico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAfipChico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAgregar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAgregar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAnterior24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAnterior24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAplicacionIcon300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAplicacionIcon300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageArqueoCaja32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageArqueoCaja32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAsistenciaManual32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAsistenciaManual32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAsistenciaPresencial32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAsistenciaPresencial32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageBorrar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageBorrar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageBuscar16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageBuscar16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCancelar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCancelar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCardonerSistemas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCardonerSistemas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCerrar16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCerrar16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCerrar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCerrar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageComisionDirectiva32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageComisionDirectiva32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCopiar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCopiar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageDatabaseLoginInfo48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDatabaseLoginInfo48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageDatabaseSelect48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDatabaseSelect48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageDocumentaciones32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDocumentaciones32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageElemento32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageElemento32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageFacturaCompra32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageFacturaCompra32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageGuardia32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageGuardia32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageImprimir32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageImprimir32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageInicioSesion48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageInicioSesion48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageJefatura32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageJefatura32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageOrdenCompra32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageOrdenCompra32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePersona32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePersona32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePersonaHombre16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePersonaHombre16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePersonaMujer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePersonaMujer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePrevisualizar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePrevisualizar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageReporte32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageReporte32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSancion32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSancion32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSiguiente24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSiguiente24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSiniestro32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSiniestro32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageTablas32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageTablas32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageUnidad32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageUnidad32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageWindowsCloseAll16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWindowsCloseAll16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha realizado cambios en los datos y seleccionó cancelar.{0}{0}¿Confirma que desea descartar los cambios?.
        '''</summary>
        Friend ReadOnly Property STRING_CONFIRMAR_CANCELACION_DATOS() As String
            Get
                Return ResourceManager.GetString("STRING_CONFIRMAR_CANCELACION_DATOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ambas direcciones de e-mail.
        '''</summary>
        Friend ReadOnly Property STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_AMBAS() As String
            Get
                Return ResourceManager.GetString("STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_AMBAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to una de las direcciones de e-mail.
        '''</summary>
        Friend ReadOnly Property STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_CUALQUIERA() As String
            Get
                Return ResourceManager.GetString("STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_CUALQUIERA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to la dirección de e-mail 1.
        '''</summary>
        Friend ReadOnly Property STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_EMAIL1() As String
            Get
                Return ResourceManager.GetString("STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_EMAIL1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to la dirección de e-mail 2.
        '''</summary>
        Friend ReadOnly Property STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_EMAIL2() As String
            Get
                Return ResourceManager.GetString("STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_EMAIL2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No enviar.
        '''</summary>
        Friend ReadOnly Property STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_NO() As String
            Get
                Return ResourceManager.GetString("STRING_ENTIDAD_COMPROBANTE_ENVIAREMAIL_NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login failed for user.
        '''</summary>
        Friend ReadOnly Property STRING_ERROR_DB_LOGIN_MESSAGE() As String
            Get
                Return ResourceManager.GetString("STRING_ERROR_DB_LOGIN_MESSAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al guardar los cambios en la Base de Datos..
        '''</summary>
        Friend ReadOnly Property STRING_ERROR_SAVING_CHANGES() As String
            Get
                Return ResourceManager.GetString("STRING_ERROR_SAVING_CHANGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Femenino.
        '''</summary>
        Friend ReadOnly Property STRING_GENERO_FEMENINO() As String
            Get
                Return ResourceManager.GetString("STRING_GENERO_FEMENINO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Masculino.
        '''</summary>
        Friend ReadOnly Property STRING_GENERO_MASCULINO() As String
            Get
                Return ResourceManager.GetString("STRING_GENERO_MASCULINO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Todas».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_ALL_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_ALL_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Todos».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_ALL_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_ALL_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Completa».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_COMPLETE_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_COMPLETE_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Completo».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_COMPLETE_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_COMPLETE_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Vacía».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_EMPTY_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_EMPTY_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Vacío».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_EMPTY_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_EMPTY_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_END_CHAR() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_END_CHAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Nueva».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NEW_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NEW_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Nuevo».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NEW_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NEW_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ----------.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS10() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS2() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --------------------.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS20() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -----.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS5() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Ninguna».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Ninguno».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «No especifica».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NOT_SPECIFIED() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NOT_SPECIFIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Otra».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_OTHER_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_OTHER_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Otro».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_OTHER_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_OTHER_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_START_CHAR() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_START_CHAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend ReadOnly Property STRING_NO() As String
            Get
                Return ResourceManager.GetString("STRING_NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compra.
        '''</summary>
        Friend ReadOnly Property STRING_OPERACIONTIPO_COMPRA() As String
            Get
                Return ResourceManager.GetString("STRING_OPERACIONTIPO_COMPRA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Venta.
        '''</summary>
        Friend ReadOnly Property STRING_OPERACIONTIPO_VENTA() As String
            Get
                Return ResourceManager.GetString("STRING_OPERACIONTIPO_VENTA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activo.
        '''</summary>
        Friend ReadOnly Property STRING_PERSONA_ESTADO_ACTIVO() As String
            Get
                Return ResourceManager.GetString("STRING_PERSONA_ESTADO_ACTIVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Desconocido».
        '''</summary>
        Friend ReadOnly Property STRING_PERSONA_ESTADO_DESCONOCIDO() As String
            Get
                Return ResourceManager.GetString("STRING_PERSONA_ESTADO_DESCONOCIDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Activo.
        '''</summary>
        Friend ReadOnly Property STRING_PERSONA_ESTADO_INACTIVO() As String
            Get
                Return ResourceManager.GetString("STRING_PERSONA_ESTADO_INACTIVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Sin establecer».
        '''</summary>
        Friend ReadOnly Property STRING_VALOR_ESTABLECIDO_NO() As String
            Get
                Return ResourceManager.GetString("STRING_VALOR_ESTABLECIDO_NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Establecido».
        '''</summary>
        Friend ReadOnly Property STRING_VALOR_ESTABLECIDO_SI() As String
            Get
                Return ResourceManager.GetString("STRING_VALOR_ESTABLECIDO_SI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sí.
        '''</summary>
        Friend ReadOnly Property STRING_YES() As String
            Get
                Return ResourceManager.GetString("STRING_YES", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
