'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class CSBomberosContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CSBomberosContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DocumentoTipo() As DbSet(Of DocumentoTipo)
    Public Overridable Property Localidad() As DbSet(Of Localidad)
    Public Overridable Property Log() As DbSet(Of Log)
    Public Overridable Property Parametro() As DbSet(Of Parametro)
    Public Overridable Property Provincia() As DbSet(Of Provincia)
    Public Overridable Property Reporte() As DbSet(Of Reporte)
    Public Overridable Property ReporteGrupo() As DbSet(Of ReporteGrupo)
    Public Overridable Property ReporteParametro() As DbSet(Of ReporteParametro)
    Public Overridable Property Usuario() As DbSet(Of Usuario)
    Public Overridable Property UsuarioGrupo() As DbSet(Of UsuarioGrupo)
    Public Overridable Property UsuarioGrupoPermiso() As DbSet(Of UsuarioGrupoPermiso)
    Public Overridable Property Cuartel() As DbSet(Of Cuartel)
    Public Overridable Property Parentesco() As DbSet(Of Parentesco)
    Public Overridable Property Persona() As DbSet(Of Persona)
    Public Overridable Property PersonaFamiliar() As DbSet(Of PersonaFamiliar)
    Public Overridable Property Area() As DbSet(Of Area)
    Public Overridable Property Cargo() As DbSet(Of Cargo)
    Public Overridable Property CargoJerarquia() As DbSet(Of CargoJerarquia)
    Public Overridable Property Elemento() As DbSet(Of Elemento)
    Public Overridable Property NivelEstudio() As DbSet(Of NivelEstudio)
    Public Overridable Property PersonaAccidente() As DbSet(Of PersonaAccidente)
    Public Overridable Property PersonaAltaBaja() As DbSet(Of PersonaAltaBaja)
    Public Overridable Property PersonaAscenso() As DbSet(Of PersonaAscenso)
    Public Overridable Property Ubicacion() As DbSet(Of Ubicacion)
    Public Overridable Property Unidad() As DbSet(Of Unidad)
    Public Overridable Property UnidadTipo() As DbSet(Of UnidadTipo)
    Public Overridable Property CombustibleTipo() As DbSet(Of CombustibleTipo)
    Public Overridable Property SubUbicacion() As DbSet(Of SubUbicacion)
    Public Overridable Property ModoAdquisicion() As DbSet(Of ModoAdquisicion)
    Public Overridable Property CalificacionConcepto() As DbSet(Of CalificacionConcepto)
    Public Overridable Property PersonaCalificacion() As DbSet(Of PersonaCalificacion)
    Public Overridable Property PenaAplicacion() As DbSet(Of PenaAplicacion)
    Public Overridable Property Rubro() As DbSet(Of Rubro)
    Public Overridable Property SubRubro() As DbSet(Of SubRubro)
    Public Overridable Property Inventario() As DbSet(Of Inventario)
    Public Overridable Property CapacitacionNivel() As DbSet(Of CapacitacionNivel)
    Public Overridable Property CapacitacionTipo() As DbSet(Of CapacitacionTipo)
    Public Overridable Property Curso() As DbSet(Of Curso)
    Public Overridable Property LicenciaCausa() As DbSet(Of LicenciaCausa)
    Public Overridable Property LicenciaConducirCategoria() As DbSet(Of LicenciaConducirCategoria)
    Public Overridable Property PersonaBajaMotivo() As DbSet(Of PersonaBajaMotivo)
    Public Overridable Property PersonaCapacitacion() As DbSet(Of PersonaCapacitacion)
    Public Overridable Property PersonaExamen() As DbSet(Of PersonaExamen)
    Public Overridable Property PersonaLicencia() As DbSet(Of PersonaLicencia)
    Public Overridable Property PersonaLicenciaConducirCategoria() As DbSet(Of PersonaLicenciaConducirCategoria)
    Public Overridable Property PersonaSancion() As DbSet(Of PersonaSancion)
    Public Overridable Property SancionTipo() As DbSet(Of SancionTipo)
    Public Overridable Property UnidadUso() As DbSet(Of UnidadUso)
    Public Overridable Property Alarma() As DbSet(Of Alarma)
    Public Overridable Property UsuarioParametro() As DbSet(Of UsuarioParametro)
    Public Overridable Property UnidadBajaMotivo() As DbSet(Of UnidadBajaMotivo)
    Public Overridable Property DocumentacionTipo() As DbSet(Of DocumentacionTipo)
    Public Overridable Property PersonaHorarioLaboral() As DbSet(Of PersonaHorarioLaboral)
    Public Overridable Property PersonaVacuna() As DbSet(Of PersonaVacuna)
    Public Overridable Property PersonaVehiculo() As DbSet(Of PersonaVehiculo)
    Public Overridable Property VacunaTipo() As DbSet(Of VacunaTipo)
    Public Overridable Property VehiculoCompaniaSeguro() As DbSet(Of VehiculoCompaniaSeguro)
    Public Overridable Property VehiculoMarca() As DbSet(Of VehiculoMarca)
    Public Overridable Property VehiculoTipo() As DbSet(Of VehiculoTipo)
    Public Overridable Property EstadoCivil() As DbSet(Of EstadoCivil)
    Public Overridable Property ReporteCampo() As DbSet(Of ReporteCampo)
    Public Overridable Property TipografiaEstilo() As DbSet(Of TipografiaEstilo)
    Public Overridable Property Partido() As DbSet(Of Partido)
    Public Overridable Property CompraOrden() As DbSet(Of CompraOrden)
    Public Overridable Property CompraOrdenDetalle() As DbSet(Of CompraOrdenDetalle)
    Public Overridable Property Responsable() As DbSet(Of Responsable)
    Public Overridable Property ResponsableTipo() As DbSet(Of ResponsableTipo)
    Public Overridable Property Modulo() As DbSet(Of Modulo)
    Public Overridable Property Caja() As DbSet(Of Caja)
    Public Overridable Property CajaArqueo() As DbSet(Of CajaArqueo)
    Public Overridable Property CajaArqueoDetalle() As DbSet(Of CajaArqueoDetalle)
    Public Overridable Property Siniestro() As DbSet(Of Siniestro)
    Public Overridable Property SiniestroAsistencia() As DbSet(Of SiniestroAsistencia)
    Public Overridable Property SiniestroAsistenciaTipo() As DbSet(Of SiniestroAsistenciaTipo)
    Public Overridable Property SiniestroRubro() As DbSet(Of SiniestroRubro)
    Public Overridable Property SiniestroTipo() As DbSet(Of SiniestroTipo)
    Public Overridable Property Academia() As DbSet(Of Academia)
    Public Overridable Property AcademiaAsistencia() As DbSet(Of AcademiaAsistencia)
    Public Overridable Property AcademiaAsistenciaTipo() As DbSet(Of AcademiaAsistenciaTipo)
    Public Overridable Property AcademiaTipo() As DbSet(Of AcademiaTipo)
    Public Overridable Property PersonaLicenciaEspecial() As DbSet(Of PersonaLicenciaEspecial)
    Public Overridable Property AcademiaAsistenciaTipoPuntaje() As DbSet(Of AcademiaAsistenciaTipoPuntaje)
    Public Overridable Property SiniestroAsistenciaTipoPuntaje() As DbSet(Of SiniestroAsistenciaTipoPuntaje)
    Public Overridable Property AsistenciaMetodo() As DbSet(Of AsistenciaMetodo)
    Public Overridable Property SiniestroAsistenciaTipoPuntajeClave() As DbSet(Of SiniestroAsistenciaTipoPuntajeClave)
    Public Overridable Property SiniestroClave() As DbSet(Of SiniestroClave)
    Public Overridable Property Comprobante() As DbSet(Of Comprobante)
    Public Overridable Property ComprobanteAplicacion() As DbSet(Of ComprobanteAplicacion)
    Public Overridable Property ComprobanteTipo() As DbSet(Of ComprobanteTipo)
    Public Overridable Property Entidad() As DbSet(Of Entidad)
    Public Overridable Property Articulo() As DbSet(Of Articulo)
    Public Overridable Property Banco() As DbSet(Of Banco)
    Public Overridable Property Cheque() As DbSet(Of Cheque)
    Public Overridable Property ChequeMotivoRechazo() As DbSet(Of ChequeMotivoRechazo)
    Public Overridable Property ComprobanteDetalle() As DbSet(Of ComprobanteDetalle)
    Public Overridable Property ComprobanteMedioPago() As DbSet(Of ComprobanteMedioPago)
    Public Overridable Property MedioPago() As DbSet(Of MedioPago)
    Public Overridable Property Concepto() As DbSet(Of Concepto)
    Public Overridable Property CategoriaIVA() As DbSet(Of CategoriaIVA)
    Public Overridable Property Numerador() As DbSet(Of Numerador)
    Public Overridable Property CuentaBancariaTipo() As DbSet(Of CuentaBancariaTipo)
    Public Overridable Property SancionMotivo() As DbSet(Of SancionMotivo)
    Public Overridable Property PersonaHuellaDigital() As DbSet(Of PersonaHuellaDigital)
    Public Overridable Property OrdenGeneral() As DbSet(Of OrdenGeneral)
    Public Overridable Property OrdenGeneralCategoria() As DbSet(Of OrdenGeneralCategoria)
    Public Overridable Property Resolucion() As DbSet(Of Resolucion)
    Public Overridable Property OrdenGeneralRelacion() As DbSet(Of OrdenGeneralRelacion)
    Public Overridable Property SiniestroDaminificadoEstado() As DbSet(Of SiniestroDaminificadoEstado)
    Public Overridable Property SiniestroDamnificado() As DbSet(Of SiniestroDamnificado)
    Public Overridable Property SiniestroSolicitudForma() As DbSet(Of SiniestroSolicitudForma)
    Public Overridable Property SiniestroUbicacionTipo() As DbSet(Of SiniestroUbicacionTipo)
    Public Overridable Property SiniestroVehiculo() As DbSet(Of SiniestroVehiculo)
    Public Overridable Property SiniestroVehiculoMarca() As DbSet(Of SiniestroVehiculoMarca)
    Public Overridable Property SiniestroVehiculoTipo() As DbSet(Of SiniestroVehiculoTipo)

    Public Overridable Function PersonasObtenerPorCuartelYEstado(iDCuartel As Nullable(Of Byte), soloEstadoActivo As Nullable(Of Boolean)) As ObjectResult(Of PersonasObtenerPorCuartelYEstado_Result)
        Dim iDCuartelParameter As ObjectParameter = If(iDCuartel.HasValue, New ObjectParameter("IDCuartel", iDCuartel), New ObjectParameter("IDCuartel", GetType(Byte)))

        Dim soloEstadoActivoParameter As ObjectParameter = If(soloEstadoActivo.HasValue, New ObjectParameter("SoloEstadoActivo", soloEstadoActivo), New ObjectParameter("SoloEstadoActivo", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PersonasObtenerPorCuartelYEstado_Result)("PersonasObtenerPorCuartelYEstado", iDCuartelParameter, soloEstadoActivoParameter)
    End Function

    Public Overridable Function AcademiaAgregarAsistenciaDePersonas(iDAcademia As Nullable(Of Integer), iDUsuario As Nullable(Of Short)) As Integer
        Dim iDAcademiaParameter As ObjectParameter = If(iDAcademia.HasValue, New ObjectParameter("IDAcademia", iDAcademia), New ObjectParameter("IDAcademia", GetType(Integer)))

        Dim iDUsuarioParameter As ObjectParameter = If(iDUsuario.HasValue, New ObjectParameter("IDUsuario", iDUsuario), New ObjectParameter("IDUsuario", GetType(Short)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AcademiaAgregarAsistenciaDePersonas", iDAcademiaParameter, iDUsuarioParameter)
    End Function

    Public Overridable Function AcademiaObtenerPersonasParaAsistencia(iDAcademia As Nullable(Of Integer)) As ObjectResult(Of AcademiaObtenerPersonasParaAsistencia_Result)
        Dim iDAcademiaParameter As ObjectParameter = If(iDAcademia.HasValue, New ObjectParameter("IDAcademia", iDAcademia), New ObjectParameter("IDAcademia", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AcademiaObtenerPersonasParaAsistencia_Result)("AcademiaObtenerPersonasParaAsistencia", iDAcademiaParameter)
    End Function

    Public Overridable Function SiniestroAgregarAsistenciaDePersonas(iDSiniestro As Nullable(Of Integer), iDUsuario As Nullable(Of Short)) As Integer
        Dim iDSiniestroParameter As ObjectParameter = If(iDSiniestro.HasValue, New ObjectParameter("IDSiniestro", iDSiniestro), New ObjectParameter("IDSiniestro", GetType(Integer)))

        Dim iDUsuarioParameter As ObjectParameter = If(iDUsuario.HasValue, New ObjectParameter("IDUsuario", iDUsuario), New ObjectParameter("IDUsuario", GetType(Short)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SiniestroAgregarAsistenciaDePersonas", iDSiniestroParameter, iDUsuarioParameter)
    End Function

    Public Overridable Function SiniestroObtenerPersonasParaAsistencia(iDSiniestro As Nullable(Of Integer)) As ObjectResult(Of SiniestroObtenerPersonasParaAsistencia_Result)
        Dim iDSiniestroParameter As ObjectParameter = If(iDSiniestro.HasValue, New ObjectParameter("IDSiniestro", iDSiniestro), New ObjectParameter("IDSiniestro", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SiniestroObtenerPersonasParaAsistencia_Result)("SiniestroObtenerPersonasParaAsistencia", iDSiniestroParameter)
    End Function

    Public Overridable Function PersonasObtenerConEstadoYJerarquia() As ObjectResult(Of PersonasObtenerConEstadoYJerarquia_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PersonasObtenerConEstadoYJerarquia_Result)("PersonasObtenerConEstadoYJerarquia")
    End Function

End Class
