'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entidad
    Public Property IDEntidad As Short
    Public Property Nombre As String
    Public Property Cuit As Nullable(Of Long)
    Public Property IDCategoriaIVA As Nullable(Of Byte)
    Public Property Telefono1 As String
    Public Property Telefono2 As String
    Public Property Email1 As String
    Public Property Email2 As String
    Public Property DomicilioCalle1 As String
    Public Property DomicilioNumero As String
    Public Property DomicilioPiso As String
    Public Property DomicilioDepartamento As String
    Public Property DomicilioCalle2 As String
    Public Property DomicilioCalle3 As String
    Public Property DomicilioCalleCompleto As String
    Public Property DomicilioCodigoPostal As String
    Public Property DomicilioIDProvincia As Nullable(Of Byte)
    Public Property DomicilioIDLocalidad As Nullable(Of Short)
    Public Property HabilitarCompra As Boolean
    Public Property HabilitarVenta As Boolean
    Public Property CuentaBancariaIDBanco As Nullable(Of Short)
    Public Property CuentaBancariaIDTipo As Nullable(Of Byte)
    Public Property CuentaBancariaSucursal As Nullable(Of Short)
    Public Property CuentaBancariaNumero As String
    Public Property CuentaBancariaCbu As String
    Public Property CuentaBancariaCbuAlias As String
    Public Property CuentaBancariaCuit As Nullable(Of Long)
    Public Property CuentaBancariaTitular As String
    Public Property Notas As String
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property CompraOrdenes As ICollection(Of CompraOrden) = New HashSet(Of CompraOrden)
    Public Overridable Property Comprobantes As ICollection(Of Comprobante) = New HashSet(Of Comprobante)
    Public Overridable Property Localidad As Localidad
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property CategoriaIVA As CategoriaIVA
    Public Overridable Property CuentaBancariaTipo As CuentaBancariaTipo

End Class
