'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaVacuna
    Public Property IDPersona As Integer
    Public Property IDVacuna As Byte
    Public Property IDVacunaTipo As Byte
    Public Property Lote As String
    Public Property DosisNumero As Nullable(Of Byte)
    Public Property Fecha As Nullable(Of Date)
    Public Property Vencimiento As Nullable(Of Date)
    Public Property Notas As String
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property VacunaTipo As VacunaTipo
    Public Overridable Property Persona As Persona

End Class
