'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaAccidente
    Public Property IDPersona As Integer
    Public Property IDAccidente As Short
    Public Property Fecha As Date
    Public Property Diagnostico As String
    Public Property LibroNumero As String
    Public Property FolioNumero As String
    Public Property ActaNumero As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property Capacidad As String
    Public Property DisminucionFisica As String
    Public Property Notas As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Persona As Persona
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
