'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reporte
    Public Property IDReporte As Short
    Public Property Nombre As String
    Public Property Archivo As String
    Public Property OrigenDatos As String
    Public Property IDTipografiaEstilo As Nullable(Of Byte)
    Public Property MaximoRegistrosDetalle As Nullable(Of Byte)
    Public Property AgruparPorCampo As String
    Public Property MostrarEnVisor As Boolean
    Public Property Orden As Nullable(Of Byte)

    Public Overridable Property ReporteParametros As ICollection(Of ReporteParametro) = New HashSet(Of ReporteParametro)
    Public Overridable Property ReporteCampos As ICollection(Of ReporteCampo) = New HashSet(Of ReporteCampo)
    Public Overridable Property TipografiaEstilo As TipografiaEstilo
    Public Overridable Property UsuarioGrupos As ICollection(Of UsuarioGrupo) = New HashSet(Of UsuarioGrupo)
    Public Overridable Property ReporteGrupos As ICollection(Of ReporteGrupo) = New HashSet(Of ReporteGrupo)

End Class
