'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Responsable
    Public Property IDResponsable As Byte
    Public Property IDResponsableTipo As Byte
    Public Property IDCuartel As Nullable(Of Byte)
    Public Property IDPersona As Nullable(Of Integer)
    Public Property PersonaOtra As String
    Public Property Notas As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Cuartel As Cuartel
    Public Overridable Property Persona As Persona
    Public Overridable Property ResponsableTipo As ResponsableTipo
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
