'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SiniestroAsistenciaTipoPuntajeClave
    Public Property IDSiniestroAsistenciaTipo As Byte
    Public Property IDSiniestroAsistenciaTipoPuntaje As Byte
    Public Property IDSiniestroClave As Byte
    Public Property Puntaje As Decimal

    Public Overridable Property SiniestroAsistenciaTipoPuntaje As SiniestroAsistenciaTipoPuntaje
    Public Overridable Property SiniestroClave As SiniestroClave

End Class
