'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SiniestroSolicitudForma
    Public Property IdSiniestroSolicitudForma As Byte
    Public Property Nombre As String
    Public Property Notas As String
    Public Property EsActivo As Boolean
    Public Property IdUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IdUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Siniestros As ICollection(Of Siniestro) = New HashSet(Of Siniestro)
    Public Overridable Property Usuario As Usuario
    Public Overridable Property Usuario1 As Usuario

End Class
