'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SiniestroDamnificado
    Public Property IdSiniestro As Integer
    Public Property IdDamnificado As Byte
    Public Property Genero As String
    Public Property Apellido As String
    Public Property Nombre As String
    Public Property IdDocumentoTipo As Nullable(Of Byte)
    Public Property DocumentoNumero As String
    Public Property Edad As Nullable(Of Byte)
    Public Property EsMenor As Nullable(Of Boolean)
    Public Property Trasladado As Nullable(Of Boolean)
    Public Property IdSiniestroDaminificadoEstado As Byte

    Public Overridable Property DocumentoTipo1 As DocumentoTipo
    Public Overridable Property Siniestro As Siniestro
    Public Overridable Property SiniestroDaminificadoEstado As SiniestroDaminificadoEstado

End Class
